### ISSUE TITLE
get_resistor.pyがラズベリーパイで動かない

### ISSUE THREAD

**Issue by opuyoshi** [opuyoshi/colorcode_detect#2]
# 問題点
get_resistor.pyを実行させるとプログラムの途中でエラーが出て止まる

> Traceback (most recent call last):
  File "get_resistor.py", line 53, in <module>
    cut_img = rectangle_img(pre_img, img_copy)
  File "get_resistor.py", line 29, in rectangle_img
    cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

windowsで実行させると動くので何が原因なのか調査する必要がある。

# 提案
raspberry piの環境でもう一度プログラムを作成する。

**Comment by opuyoshi** [comment]
以下の環境でget_resistor.pyを動かした．
> Description:	Raspbian GNU/Linux 10 (buster)

またopenCVは[この方法](https://qiita.com/masaru/items/658b24b0806144cfeb1c)と同じ手順でインストールした．

`python3 get_resistor.py ./images/nail_cutting.jpg`を実行すると以下のようなエラーが出た．
> raceback (most recent call last):
  File "get_resistor.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

このエラーに対して魔法のコマンドを追加してプログラムを実行させるとエラーを吐くことなく実行することができた．
`LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3 get_resistor.py ./images/nail_cutting.jpg`

魔法すごい()
